TRAIN_DATA = '../data/train.csv'
TEST_DATA = '../data/test.csv'
PROCESSED_TRAIN_DATA = '../data/processed_train_data.csv'
PROCESSED_TEST_DATA = '../data/processed_test_data.csv'
MODELS_PATH = '../models/'
MODEL = 'randomforest'